import Head from "next/head";
import Content from "../components/Content/Content";
import Layout from "../components/Layout/Layout";
import Main from "../components/Main/Main";
export default function Home() {
  return (
    <Layout>
      <Head>
        <title> Facebook </title>{" "}
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>{" "}
      <main className="w-full h-auto bg-main">
        <Main />
        <Content />
      </main>{" "}
    </Layout>
  );
}
